# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe PhotosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Photo. As you add validations to Photo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {
    image: test_image,
    caption: 'test caption'
  } }

  let(:test_image) {
    Rack::Test::UploadedFile.new(Rails.root + 'spec/images/cat.jpg', 'image/jpg')
  }

  # let(:invalid_attributes) {
  #   skip("Add a hash of attributes invalid for your model")
  # }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PhotosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before(:each) do
    @photo = create(:photo, caption: "This is a photo!")
  end

  describe "GET #index" do
    it "returns a success response" do
      get :index, params: {}
      expect(response).to have_http_status(200)
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      get :show, params: { id: @photo.to_param }
      expect(response).to have_http_status(200)
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}
      expect(response).to have_http_status(200)
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      get :edit, params: { id: @photo.to_param }
      expect(response).to have_http_status(200)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Photo" do
        expect {
          post :create, params: { photo: valid_attributes }
        }.to change(Photo, :count).by(1)
      end

      it "redirects to the created photo" do
        post :create, params: { photo: valid_attributes }
        expect(response).to redirect_to(Photo.last)
      end
    end

    # context "with invalid params" do
    #   it "returns a success response (i.e. to display the 'new' template)" do
    #     post :create, params: {photo: invalid_attributes}
    #     expect(response).to have_http_status(200)
    #   end
    # end
  end

  describe "PUT #update" do
    context "with valid params" do
      # let(:new_attributes) {
      #   skip("Add a hash of attributes valid for your model")
      # }

      # it "updates the requested photo" do
      #   put :update, params: {id: @photo.to_param, photo: new_attributes}
      #   photo.reload
      #   skip("Add assertions for updated state")
      # end

      it "redirects to the photo" do
        put :update, params: { id: @photo.to_param, photo: valid_attributes }
        expect(response).to redirect_to(@photo)
      end
    end

    # context "with invalid params" do
    #   it "returns a success response (i.e. to display the 'edit' template)" do
    #     put :update, params: {id: @photo.to_param, photo: invalid_attributes}
    #     expect(response).to have_http_status(200)
    #   end
    # end
  end

  describe "DELETE #destroy" do
    it "destroys the requested photo" do
      expect {
        delete :destroy, params: { id: @photo.to_param }
      }.to change(Photo, :count).by(-1)
    end

    it "redirects to the photos list" do
      delete :destroy, params: { id: @photo.to_param }
      expect(response).to redirect_to(photos_url)
    end
  end

end
